name: CROSS BUILD
on: 
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci
env:
  BUILD_DIR: ${{ github.workspace }}/ci-build
  TZ: Asia/Shanghai
  DEBIAN_FRONTEND: noninteractive
  CI_PROJECT_DIR: ${{ github.workspace }}
  ENABLE_STATIC: 1
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Cross build
      run: |
        git submodule init &&  git submodule  update
        mkdir -p "${BUILD_DIR}"
        sudo apt install libyaml-dev -qq
        bash .github/cross_build.sh
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error 
        # name: ci-build
        path: |
          ${{ env.BUILD_DIR }}/target-binary/**/*
        retention-days: 5
    